// <auto-generated />
namespace LabDeskApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatecomments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecomments));
        
        string IMigrationMetadata.Id
        {
            get { return "201909281040434_updatecomments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
